export { default as Home } from './Home'
export { default as Game } from './Game'
export { default as GameHistory } from './GameHistory'
export { default as GameHistoryDetails } from './GameHistoryDetails'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
